// This file is included by ../browsr.js
// Global is the global contexts object

var HTMLDocumentPrototype = Object.create(DocumentPrototype, {
  captureEvents:            {configurable: false, enumerable: true, value: function captureEvents() {}},
  clear:                    {configurable: false, enumerable: true, value: function clear() {}},
  close:                    {configurable: false, enumerable: true, value: function close() {}},
  hasFocus:                 {configurable: false, enumerable: true, value: function hasFocus() {}},
  open:                     {configurable: false, enumerable: true, value: function open() {}},
  releaseEvents:            {configurable: false, enumerable: true, value: function releaseEvents() {}},
  write:                    {configurable: false, enumerable: true, value: function write() {}},
  writeln:                  {configurable: false, enumerable: true, value: function writeln() {}}
});

var document = Object.create(HTMLDocumentPrototype, {
  URL:                      {configurable: false, enumerable: true, value: null},
  activeElement:            {configurable: false, enumerable: true, value: null},
  alinkColor:               {configurable: false, enumerable: true, value: null},
  all:                      {configurable: false, enumerable: true, value: null},
  anchors:                  {configurable: false, enumerable: true, value: null},
  applets:                  {configurable: false, enumerable: true, value: null},
  attributes:               {configurable: false, enumerable: true, value: null},
  baseURI:                  {configurable: false, enumerable: true, value: null},
  bgColor:                  {configurable: false, enumerable: true, value: null},
  body:                     {configurable: false, enumerable: true, value: null},
  characterSet:             {configurable: false, enumerable: true, value: null},
  charset:                  {configurable: false, enumerable: true, value: null},
  childNodes:               {configurable: false, enumerable: true, value: null},
  compatMode:               {configurable: false, enumerable: true, value: null},
  constructor:              {configurable: false, enumerable: true, value: null},
  cookie:                   {configurable: false, enumerable: true, value: null},
  defaultCharset:           {configurable: false, enumerable: true, value: null},
  defaultView:              {configurable: false, enumerable: true, value: null},
  designMode:               {configurable: false, enumerable: true, value: null},
  dir:                      {configurable: false, enumerable: true, value: null},
  doctype:                  {configurable: false, enumerable: true, value: null},
  documentElement:          {configurable: false, enumerable: true, value: null},
  documentURI:              {configurable: false, enumerable: true, value: null},
  domain:                   {configurable: false, enumerable: true, value: null},
  embeds:                   {configurable: false, enumerable: true, value: null},
  fgColor:                  {configurable: false, enumerable: true, value: null},
  firstChild:               {configurable: false, enumerable: true, value: null},
  forms:                    {configurable: false, enumerable: true, value: null},
  head:                     {configurable: false, enumerable: true, value: null},
  height:                   {configurable: false, enumerable: true, value: null},
  images:                   {configurable: false, enumerable: true, value: null},
  implementation:           {configurable: false, enumerable: true, value: null},
  inputEncoding:            {configurable: false, enumerable: true, value: null},
  lastChild:                {configurable: false, enumerable: true, value: null},
  lastModified:             {configurable: false, enumerable: true, value: null},
  linkColor:                {configurable: false, enumerable: true, value: null},
  links:                    {configurable: false, enumerable: true, value: null},
  localName:                {configurable: false, enumerable: true, value: null},
  location:                 {configurable: false, enumerable: true, value: null},
  namespaceURI:             {configurable: false, enumerable: true, value: null},
  nextSibling:              {configurable: false, enumerable: true, value: null},
  nodeName:                 {configurable: false, enumerable: true, value: null},
  nodeType:                 {configurable: false, enumerable: true, value: null},
  nodeValue:                {configurable: false, enumerable: true, value: null},
  onabort:                  {configurable: false, enumerable: true, value: null},
  onbeforecopy:             {configurable: false, enumerable: true, value: null},
  onbeforecut:              {configurable: false, enumerable: true, value: null},
  onbeforepaste:            {configurable: false, enumerable: true, value: null},
  onblur:                   {configurable: false, enumerable: true, value: null},
  onchange:                 {configurable: false, enumerable: true, value: null},
  onclick:                  {configurable: false, enumerable: true, value: null},
  oncontextmenu:            {configurable: false, enumerable: true, value: null},
  oncopy:                   {configurable: false, enumerable: true, value: null},
  oncut:                    {configurable: false, enumerable: true, value: null},
  ondblclick:               {configurable: false, enumerable: true, value: null},
  ondrag:                   {configurable: false, enumerable: true, value: null},
  ondragend:                {configurable: false, enumerable: true, value: null},
  ondragenter:              {configurable: false, enumerable: true, value: null},
  ondragleave:              {configurable: false, enumerable: true, value: null},
  ondragover:               {configurable: false, enumerable: true, value: null},
  ondragstart:              {configurable: false, enumerable: true, value: null},
  ondrop:                   {configurable: false, enumerable: true, value: null},
  onerror:                  {configurable: false, enumerable: true, value: null},
  onfocus:                  {configurable: false, enumerable: true, value: null},
  oninput:                  {configurable: false, enumerable: true, value: null},
  oninvalid:                {configurable: false, enumerable: true, value: null},
  onkeydown:                {configurable: false, enumerable: true, value: null},
  onkeypress:               {configurable: false, enumerable: true, value: null},
  onkeyup:                  {configurable: false, enumerable: true, value: null},
  onload:                   {configurable: false, enumerable: true, value: null},
  onmousedown:              {configurable: false, enumerable: true, value: null},
  onmousemove:              {configurable: false, enumerable: true, value: null},
  onmouseout:               {configurable: false, enumerable: true, value: null},
  onmouseover:              {configurable: false, enumerable: true, value: null},
  onmouseup:                {configurable: false, enumerable: true, value: null},
  onmousewheel:             {configurable: false, enumerable: true, value: null},
  onpaste:                  {configurable: false, enumerable: true, value: null},
  onreset:                  {configurable: false, enumerable: true, value: null},
  onscroll:                 {configurable: false, enumerable: true, value: null},
  onsearch:                 {configurable: false, enumerable: true, value: null},
  onselect:                 {configurable: false, enumerable: true, value: null},
  onselectstart:            {configurable: false, enumerable: true, value: null},
  onsubmit:                 {configurable: false, enumerable: true, value: null},
  ownerDocument:            {configurable: false, enumerable: true, value: null},
  parentElement:            {configurable: false, enumerable: true, value: null},
  parentNode:               {configurable: false, enumerable: true, value: null},
  plugins:                  {configurable: false, enumerable: true, value: null},
  preferredStylesheetSet:   {configurable: false, enumerable: true, value: null},
  prefix:                   {configurable: false, enumerable: true, value: null},
  previousSibling:          {configurable: false, enumerable: true, value: null},
  readyState:               {configurable: false, enumerable: true, value: null},
  referrer:                 {configurable: false, enumerable: true, value: null},
  scripts:                  {configurable: false, enumerable: true, value: null},
  selectedStylesheetSet:    {configurable: false, enumerable: true, value: null},
  styleSheets:              {configurable: false, enumerable: true, value: null},
  textContent:              {configurable: false, enumerable: true, value: null},
  title:                    {configurable: false, enumerable: true, value: null},
  vlinkColor:               {configurable: false, enumerable: true, value: null},
  width:                    {configurable: false, enumerable: true, value: null},
  xmlEncoding:              {configurable: false, enumerable: true, value: null},
  xmlStandalone:            {configurable: false, enumerable: true, value: null},
  xmlVersion:               {configurable: false, enumerable: true, value: null}
});

Object.defineProperty(Global, 'document', {value: document, configurable: false});
